---
version: 1
deployment:
  tasks:
    - echo "Début du déploiement..."
    - export DEPLOYPATH=/home/mlzdphgn/public_html/formation/php-intro/
    - /bin/cp -R * $DEPLOYPATH
    - echo "Déploiement terminé."